### ISSUE TITLE
Malformed internal data structures cause exceptions

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta#1493]
- [ ] Improve test coverage for Cross Agent Dependencies 

when running quickstart-docker, I got the following exception

```
2019-10-17 21:36:22,162 ERROR    inmanta.util An exception occurred while handling a future: 1 validation error for Event
changes -> state
  value is not a valid dict (type=type_error.dict)
Traceback (most recent call last):
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/util.py", line 236, in handle_result
    f.result()
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/agent/agent.py", line 268, in execute
    for x in self.dependencies
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/agent/agent.py", line 268, in <dictcomp>
    for x in self.dependencies
  File "pydantic/main.py", line 275, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 785, in pydantic.main.validate_model
pydantic.error_wrappers.ValidationError: 1 validation error for Event
changes -> state
  value is not a valid dict (type=type_error.dict)
```

I assume it is either due to a Cross Agent Dependency or side effect of a cancel

[agent-cc5d24b0-8d87-404c-a078-e0c21b82f8b8.log](https://github.com/inmanta/inmanta/files/3741444/agent-cc5d24b0-8d87-404c-a078-e0c21b82f8b8.log)

**Comment by wouterdb** [comment]
to test, see https://github.com/inmanta/quickstart-docker/pull/5

checkou the branch and
```
docker-compose up
git clone https://github.com/inmanta/quickstart.git --branch docker quickstart-project
docker exec -it "inmanta_quickstart_server" bash
cd /home/inmanta/quickstart-project
inmanta-cli project create -n test
inmanta-cli environment create -n quickstart-env -p test -r https://github.com/inmanta/quickstart.git -b docker --save
inmanta -vvv  export -d
```
