### ISSUE TITLE
failure to raise double defined exception

### ISSUE THREAD

**Issue by sanderr** [inmanta/inmanta#1920]
test_module/model/_init.cf:
```
entity TestEntity:
end

implement TestEntity using test

implementation test for Test:
end
```

test_module/plugins/__init__.py:
```
from inmanta.plugins import plugin


@plugin
def test() -> "number":
    return 0
```

main.cf:
```
import test_module
```

Above results in the compilation error `'test' object has no attribute 'get_double_defined_exception'`. It seems like the compiler tries to raise a double defined exception because `test` has been defined as an implementation as well as a plugin in the same namespace, but something goes wrong while trying to raise the exception. Compiling with `-X` results in:
```
Traceback (most recent call last):
  File "/home/sander/documents/projects/inmanta/inmanta-stable/src/inmanta/app.py", line 653, in app
    options.func(options)
  File "/home/sander/documents/projects/inmanta/inmanta-stable/src/inmanta/app.py", line 270, in compile_project
    result = do_compile()
  File "/home/sander/documents/projects/inmanta/inmanta-stable/src/inmanta/compiler/__init__.py", line 47, in do_compile
    success = sched.run(compiler, statements, blocks)
  File "/home/sander/documents/projects/inmanta/inmanta-stable/src/inmanta/execute/scheduler.py", line 226, in run
    self.define_types(compiler, statements, blocks)
  File "/home/sander/documents/projects/inmanta/inmanta-stable/src/inmanta/execute/scheduler.py", line 140, in define_types
    k for k in [t.register_types() for t in definitions if isinstance(t, TypeDefinitionStatement)] if k is not None
  File "/home/sander/documents/projects/inmanta/inmanta-stable/src/inmanta/execute/scheduler.py", line 140, in <listcomp>
    k for k in [t.register_types() for t in definitions if isinstance(t, TypeDefinitionStatement)] if k is not None
  File "/home/sander/documents/projects/inmanta/inmanta-stable/src/inmanta/ast/statements/__init__.py", line 259, in register_types
    self.namespace.define_type(self.name, self.type)
  File "/home/sander/documents/projects/inmanta/inmanta-stable/src/inmanta/ast/__init__.py", line 282, in define_type
    raise newtype.get_double_defined_exception(self.defines_types[name])
AttributeError: 'test' object has no attribute 'get_double_defined_exception'
```

**Comment by wouterdb** [comment]
closed by #1935
