### ISSUE TITLE
improve error reporting on errors during typing

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta#199]
add line number tracing in this case

```
Traceback (most recent call last):
 File "/home/bart/.virtualenvs/inmanta/bin/inmanta", line 6, in <module>
   exec(compile(open(__file__).read(), __file__, 'exec'))
 File "/home/bart/workspace/inmanta/bin/inmanta", line 22, in <module>
   app()
 File "/home/bart/workspace/inmanta/src/inmanta/app.py", line 309, in app
   options.func(options)
 File "/home/bart/workspace/inmanta/src/inmanta/app.py", line 111, in compile_project
   result = do_compile()
 File "/home/bart/workspace/inmanta/src/inmanta/compiler.py", line 45, in do_compile
   success = sched.run(compiler, statements, blocks)
 File "/home/bart/workspace/inmanta/src/inmanta/execute/scheduler.py", line 142, in run
   self.define_types(compiler, statements, blocks)
 File "/home/bart/workspace/inmanta/src/inmanta/execute/scheduler.py", line 127, in define_types
   t.normalize()
 File "/home/bart/workspace/inmanta/src/inmanta/ast/entity.py", line 74, in normalize
   i.normalize()
 File "/home/bart/workspace/inmanta/src/inmanta/ast/entity.py", line 463, in normalize
   self.constraint.normalize()
 File "/home/bart/workspace/inmanta/src/inmanta/ast/statements/call.py", line 51, in normalize
   self.function = self.namespace.get_type(self.name)
 File "/home/bart/workspace/inmanta/src/inmanta/ast/__init__.py", line 96, in get_type
   raise TypeNotFoundException(name, ns)
inmanta.ast.TypeNotFoundException: could not find type std::is_instance in namespace std (None)
```

**Comment by bartv** [comment]
This bug is fixed in the current version of the compiler
