### ISSUE TITLE
Improve json decoding error reporting

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#2107]
If you submit invalid json to the API you get a 500 with a message "unable to decode request body". However, the logs are much clearer on this:

```
2020-05-07 12:40:48,270 ERROR    inmanta.protocol.rest.server An exception occured
Traceback (most recent call last):
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/protocol/rest/server.py", line 118, in _call
    message = self._transport._decode(self.request.body)
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/protocol/rest/__init__.py", line 375, in _decode
    result = cast(JsonType, json.loads(escape.to_basestring(body)))
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 9 (char 131)
```

We can at least disclose that it was a json decoding issue. Not sure if it is safe to report the detailed message that details where exactly the error is. Currently I see no issue for that, because many users of the API do not have access to the server logs.

**Comment by bartv** [comment]
@wouterdb wdyt?
