### ISSUE TITLE
Tuple index out of range in API call

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#2152]
The following call which has the environment missing trigger an tupple out of range:

```
http GET http://m1-lab.bics.inmanta.com:8888/lsm/v1/service_inventory/cloudconnect/afcb51dc-1043-42b6-bb99-b4fc88603126
HTTP/1.1 500 Internal Server Error
Content-Length: 117
Content-Type: application/json
Date: Tue, 26 May 2020 11:05:40 GMT
Server: TornadoServer/6.0.4
Vary: Accept-Encoding

{
    "message": "An unexpected error occurred in the server while processing the request: ('tuple index out of range',)"
}
```

```
2020-05-26 11:06:10,773 ERROR    inmanta.protocol.rest An exception occured during the request.
Traceback (most recent call last):
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/protocol/rest/__init__.py", line 406, in _execute_call
    await arguments.process()
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/protocol/rest/__init__.py", line 188, in process
    value = self.get_default_value(arg, i, defaults_start)
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/protocol/rest/__init__.py", line 145, in get_default_value
    return self._argspec.defaults[arg_position - default_start]
IndexError: tuple index out of range
2020-05-26 11:06:10,774 ERROR    tornado.access 500 GET /lsm/v1/service_inventory/cloudconnect/afcb51dc-1043-42b6-bb99-b4fc88603126 (192.168.25.3) 2.77ms
```

**Comment by kazaamjt** [comment]
@wouterdb suggested I could pick up this ticket.
What would be the expected behaviour?
