### ISSUE TITLE
Plugin exceptions should provide more information

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#2385]
A plugin file with for example the following content:

```python
plugin
```

Provides the following error:

```
$  inmanta compile
name 'plugin' is not defined
```

However it is not clear from the message where to look for this issue. When you provide -X is already becomes more clear:

```
Traceback (most recent call last):
...
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "project/libs/abc/plugins/__init__.py", line 8, in <module>
    plugin
NameError: name 'plugin' is not defined
```

As a developer I would expect the compiler to say for example:

```
While loading python code from module abc the following error occured:
  File "project/libs/abc/plugins/__init__.py", line 8, in <module>
    plugin
  NameError: name 'plugin' is not defined
```

So they you get:
- Context: it happened while loading python code from module ABC
- Location: file project/libs/abc/plugins/__init__.py", line 8
- Complete error: NameError: ...

**Comment by sanderr** [comment]
Adding the message and the exception type is relatively simple:
```diff
--- a/src/inmanta/module.py
+++ b/src/inmanta/module.py
@@ -28,7 +28,7 @@ from functools import lru_cache
 from io import BytesIO
 from subprocess import CalledProcessError
 from tarfile import TarFile
-from typing import Any, Dict, Iterable, Iterator, List, Mapping, NewType, Optional, Set, Tuple, Union
+from typing import Any, Dict, Iterable, Iterator, List, Mapping, NewType, Optional, Set, Tuple, Type, Union
 
 import yaml
 from pkg_resources import parse_requirements, parse_version
@@ -1126,13 +1126,27 @@ class Module(ModuleLike):
         """
         Load all plug-ins from a configuration module
         """
-        try:
-            for _, fq_mod_name in self.get_plugin_files():
+        for _, fq_mod_name in self.get_plugin_files():
+            try:
                 LOGGER.debug("Loading module %s", fq_mod_name)
                 importlib.import_module(fq_mod_name)
+            except Exception as e:
+
+                def get_fully_qualified_name(t: Type) -> str:
+                    module: Optional[str] = t.__module__
+                    name: str = t.__qualname__
+                    return name if module is None or module == "builtins" else "%s.%s" % (module, name)
 
-        except ImportError as e:
-            raise CompilerException("Unable to load all plug-ins for module %s" % self._meta["name"]) from e
+                raise CompilerException(
+                    "Unable to load all plug-ins for module `%s.`"
+                    " %s while loading %s: %s"
+                    % (
+                        self._meta["name"],
+                        get_fully_qualified_name(type(e)),
+                        fq_mod_name,
+                        e,
+                    )
+                ) from e
```

I'm not sure yet how to extract the location though.
