### ISSUE TITLE
ModuleNotFoundException is raised when we don't have access to a repository, whithout any additional explaination

### ISSUE THREAD

**Issue by edvgui** [inmanta/inmanta#2515]
When compiling a project that uses some private modules, if one of them can not be installed because of access restrictions, the error doesn't really suggest it is the case.
In the following example, the model being compiled is `inmanta-infra`, and the module we don't have access to is `netbox`:
```
Compilation failed
Traceback (most recent call last):
  File "/home/guillaume/.config/Code/User/globalStorage/inmanta.inmanta/.env/lib/python3.8/site-packages/inmanta/module.py", line 602, in load_module
    module = Module.install(
  File "/home/guillaume/.config/Code/User/globalStorage/inmanta.inmanta/.env/lib/python3.8/site-packages/inmanta/module.py", line 846, in install
    raise InvalidModuleException("could not locate module with name: %s" % modulename)
inmanta.module.InvalidModuleException: could not locate module with name: netbox

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guillaume/.config/Code/User/globalStorage/inmanta.inmanta/.env/lib/python3.8/site-packages/inmanta/module.py", line 574, in load_module_recursive
    module = self.get_module(module_name)
  File "/home/guillaume/.config/Code/User/globalStorage/inmanta.inmanta/.env/lib/python3.8/site-packages/inmanta/module.py", line 549, in get_module
    return self.load_module(module_name)
  File "/home/guillaume/.config/Code/User/globalStorage/inmanta.inmanta/.env/lib/python3.8/site-packages/inmanta/module.py", line 608, in load_module
    raise InvalidModuleException("Could not load module %s" % module_name) from e
inmanta.module.InvalidModuleException: Could not load module netbox

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/guillaume/Documents/vscode-inmanta/server/src/inmantals/server.py", line 172, in compile_and_anchor
    await asyncio.get_event_loop().run_in_executor(self.threadpool, sync_compile_and_anchor)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/guillaume/Documents/vscode-inmanta/server/src/inmantals/server.py", line 137, in sync_compile_and_anchor
    (statements, blocks) = compiler_instance.compile()
  File "/home/guillaume/.config/Code/User/globalStorage/inmanta.inmanta/.env/lib/python3.8/site-packages/inmanta/compiler/__init__.py", line 189, in compile
    project.load()
  File "/home/guillaume/.config/Code/User/globalStorage/inmanta.inmanta/.env/lib/python3.8/site-packages/inmanta/module.py", line 484, in load
    self.get_complete_ast()
  File "/home/guillaume/.config/Code/User/globalStorage/inmanta.inmanta/.env/lib/python3.8/site-packages/inmanta/module.py", line 529, in get_complete_ast
    for _, nstmt, nb in self.load_module_recursive(imports):
  File "/home/guillaume/.config/Code/User/globalStorage/inmanta.inmanta/.env/lib/python3.8/site-packages/inmanta/module.py", line 588, in load_module_recursive
    raise ModuleNotFoundException(ns, imp, e)
inmanta.ast.ModuleNotFoundException: could not find module netbox::install (reported in import netbox::install (/home/guillaume/Documents/inmanta-infra/libs/infra/model/mgmt.cf:2))
```

Further investigation is required, but one thing to note is that Gitlab will show a 404 error when someone tries to access a reporitories whithout the required persmissions. (At least through the GUI, didn't try for a `git clone`)

**Comment by bartv** [comment]
The module is not found, in this case gitlab does not tell you that it does exist. So I do not see a way that you can report this

**Comment by edvgui** [comment]
Me neither, the suggestion of @arnaudsjs is that we could maybe say to the user that this is one of the possible reason.

**Comment by bartv** [comment]
Well, that is then a never ending story because other reasons are:
- you did not configure your repos correct
- you did not configure the proxy correct
- there might be a firewall in between
- ...

**Comment by edvgui** [comment]
Neither of @arnaudsjs and me has a strong opinion against that last comment, so I am closing the issue
