### ISSUE TITLE
Double assignment is not reported

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#283]
```
h = std::Host(name="test", os=std::linux)
h = "test"
std::print(h.name)
```

This should report something like h is already defined. Instead it shows the following:
```
Traceback (most recent call last):
  File "/home/bart/.virtualenvs/inmanta/bin/inmanta", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/home/bart/workspace/inmanta/bin/inmanta", line 22, in <module>
    app()
  File "/home/bart/workspace/inmanta/src/inmanta/app.py", line 358, in app
    options.func(options)
  File "/home/bart/workspace/inmanta/src/inmanta/app.py", line 116, in compile_project
    result = do_compile()
  File "/home/bart/workspace/inmanta/src/inmanta/compiler.py", line 45, in do_compile
    success = sched.run(compiler, statements, blocks)
  File "/home/bart/workspace/inmanta/src/inmanta/execute/scheduler.py", line 197, in run
    next.execute()
  File "/home/bart/workspace/inmanta/src/inmanta/execute/runtime.py", line 429, in execute
    for (k, v) in self.requires.items()}, self.resolver, self.queue_scheduler, self.target)
  File "/home/bart/workspace/inmanta/src/inmanta/ast/variables.py", line 98, in resume
    attr = obj.get_attribute(self.attribute)
AttributeError: 'str' object has no attribute 'get_attribute'
```

**Comment by wouterdb** [comment]
this is a tricky one.

It is actually #282 which produces the exception.

The execution order is
```
h = "test"
std::print(h.name)
```
which is #282 

if the code would be
```
h = "test"
h = std::Host(name="test", os=std::linux)
```
the exception is as expected
```
Value set twice: old value: test (set at (/tmp/tmppla4gw5m/main.cf:3)), new value: std::Host (instantiated at /tmp/tmppla4gw5m/main.cf:2) (set at (/tmp/tmppla4gw5m/main.cf:2)) (reported in Construct(std::Host) (/tmp/tmppla4gw5m/main.cf:2))
```

To make sure the exception is always the second, we would have to introduce some static type checking.  Implemenation wise, this would not be difficult, but it would take some consideration as to what and how we want to do static checks.

**Comment by bartv** [comment]
This is fixed in the current version of the compiler
