### ISSUE TITLE
Type missing error does not always report the location

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#558]
```
Traceback (most recent call last):
  File "/home/bart/.virtualenvs/inmanta/bin/inmanta", line 11, in <module>
    load_entry_point('inmanta', 'console_scripts', 'inmanta')()
  File "/home/bart/workspace/inmanta/src/inmanta/app.py", line 382, in app
    options.func(options)
  File "/home/bart/workspace/inmanta/src/inmanta/app.py", line 128, in compile_project
    raise e
  File "/home/bart/workspace/inmanta/src/inmanta/app.py", line 120, in compile_project
    result = do_compile()
  File "/home/bart/workspace/inmanta/src/inmanta/compiler.py", line 45, in do_compile
    success = sched.run(compiler, statements, blocks)
  File "/home/bart/workspace/inmanta/src/inmanta/execute/scheduler.py", line 178, in run
    self.define_types(compiler, statements, blocks)
  File "/home/bart/workspace/inmanta/src/inmanta/execute/scheduler.py", line 148, in define_types
    d.evaluate()
  File "/home/bart/workspace/inmanta/src/inmanta/ast/statements/define.py", line 181, in evaluate
    cls = self.namespace.get_type(self.entity)
  File "/home/bart/workspace/inmanta/src/inmanta/ast/__init__.py", line 153, in get_type
    raise TypeNotFoundException(name, self)
inmanta.ast.TypeNotFoundException: could not find type OpenstackSite in namespace appinfra
```

**Comment by bartv** [comment]
This is a duplicate of #399
