### ISSUE TITLE
Log the exception trace when get_provider excepts

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#714]
In agent.ResourceAction._execute (and maybe other places). ctx.exception does not log the trace

**Comment by wouterdb** [comment]
I can not reproduce this bug

When deploying a resource with no handler

In the agent log
'''
2018-09-04 16:02:05,689 ERROR   Unable to find a handler for exp::Test[internal,test=test_value_test],v=1536069622
Traceback (most recent call last):
  File "/home/wouter/projects/inmanta/src/inmanta/agent/agent.py", line 105, in _execute
    provider = yield self.scheduler.agent.get_provider(self.resource)
  File "/home/wouter/.virtualenvs/inmanta-x/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/wouter/.virtualenvs/inmanta-x/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/home/wouter/.virtualenvs/inmanta-x/lib/python3.6/site-packages/tornado/gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/wouter/projects/inmanta/src/inmanta/agent/agent.py", line 426, in get_provider
    provider = yield self.provider_thread_pool.submit(handler.Commander.get_provider, self._cache, self, resource)
  File "/home/wouter/.virtualenvs/inmanta-x/lib/python3.6/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib64/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib64/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/wouter/projects/inmanta/src/inmanta/agent/handler.py", line 814, in get_provider
    raise Exception("No resource handler registered for resource of type %s" % resource_type)
Exception: No resource handler registered for resource of type exp::Test
'''
on the server:
![Selection_148.png](https://images.zenhubusercontent.com/5a7d57de4b5806bc2bc6446b/9bdc7072-cc9e-4582-9e2f-adbfa38304e8)

test case on brach

**Comment by wouterdb** [comment]
can not reproduce
