### ISSUE TITLE
Wrong log statement in agent causes log lines to be lost on undeployable resource. 

### ISSUE THREAD

**Issue by wouterdb** [inmanta/inmanta#736]
https://github.com/inmanta/inmanta/blame/828df589d75984c346ae4eb069d7f827dda1dcff/src/inmanta/agent/agent.py#L510

```
2018-09-24 09:12:40,489 ERROR   An exception occurred while handling a future: 'NoneType' object has no attribute '__context__'
Traceback (most recent call last):
  File "/opt/inmanta/lib64/python3.4/site-packages/inmanta/protocol.py", line 742, in handle_result
    f.result()
  File "/opt/inmanta/lib64/python3.4/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/opt/inmanta/lib64/python3.4/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/opt/inmanta/lib64/python3.4/site-packages/inmanta/agent/agent.py", line 510, in do_run_dryrun
    resource_id=res["id"], status=res["status"])
  File "/opt/inmanta/lib64/python3.4/site-packages/inmanta/agent/handler.py", line 299, in exception
    self.error(msg, *args, exc_info=exc_info, **kwargs)
  File "/opt/inmanta/lib64/python3.4/site-packages/inmanta/agent/handler.py", line 293, in error
    self.log_msg(logging.ERROR, msg, args, kwargs)
  File "/opt/inmanta/lib64/python3.4/site-packages/inmanta/agent/handler.py", line 244, in log_msg
    kwargs["traceback"] = traceback.format_exc()
  File "/usr/lib64/python3.4/traceback.py", line 256, in format_exc
    return "".join(format_exception(*sys.exc_info(), limit=limit, chain=chain))
  File "/usr/lib64/python3.4/traceback.py", line 181, in format_exception
    return list(_format_exception_iter(etype, value, tb, limit, chain))
  File "/usr/lib64/python3.4/traceback.py", line 146, in _format_exception_iter
    for value, tb in values:
  File "/usr/lib64/python3.4/traceback.py", line 125, in _iter_chain
    context = exc.__context__
AttributeError: 'NoneType' object has no attribute '__context__'
2018-09-24 09:12:40,489 DEBUG   Installing handler vcenter::DVPortgroupConfigSpec for inmanta_plugins.vcenter
```

**Comment by bartv** [comment]
Now here: https://github.com/inmanta/inmanta/blob/master/src/inmanta/agent/agent.py#L758
