### ISSUE TITLE
env activation does not work correct

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#861]
The test case test_basic_install installs lorem and the other test modules inside the calling python env and not in the created virtual env.

![image](https://user-images.githubusercontent.com/10819/50305759-1fff3280-0494-11e9-88a4-7f1b3256763d.png)

**Comment by wouterdb** [comment]
can not reproduce

![image](https://user-images.githubusercontent.com/1788254/50339535-364ed200-0518-11e9-9489-ca797680bd92.png)


make sure that the venv you are in is a venv and not a virtualenv, as venv creation fails in a virtualenv 
with the following error

```
env.py                      73 ERROR    Unable to create new virtualenv at /tmp/pytest-of-wouter/pytest-2/test_basic_install0/env1 (Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.6/ensurepip/__main__.py", line 5, in <module>
    sys.exit(ensurepip._main())
  File "/usr/lib64/python3.6/ensurepip/__init__.py", line 232, in _main
    default_pip=args.default_pip,
  File "/usr/lib64/python3.6/ensurepip/__init__.py", line 103, in _bootstrap
    dep_records = rewheel.find_system_records([p[0] for p in _PROJECTS])
  File "/usr/lib64/python3.6/ensurepip/rewheel/__init__.py", line 39, in find_system_records
    sys_sitepack = site.getsitepackages([sys.base_prefix, sys.base_exec_prefix])
AttributeError: module 'site' has no attribute 'getsitepackages'
)
```
