### ISSUE TITLE
Client call from handler results in error in tornado http client

### ISSUE THREAD

**Issue by bartv** [inmanta/inmanta#956]
```
2019-02-25 13:15:49,615 INFO     inmanta.agent.handler Setting parameter fsm_clearwater state to boot
2019-02-25 13:15:49,617 ERROR    inmanta.protocol.rest Failed to send request
Traceback (most recent call last):
  File "/opt/inmanta/lib64/python3.6/site-packages/inmanta/protocol/rest/client.py", line 127, in call
    response = yield client.fetch(request)
  File "/opt/inmanta/lib64/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/opt/inmanta/lib64/python3.6/site-packages/tornado/simple_httpclient.py", line 264, in run
    timeout = min(self.request.connect_timeout, self.request.request_timeout)
TypeError: '<' not supported between instances of 'int' and 'AsyncIOMainLoop'
```

**Comment by bartv** [comment]
This is caused by an error in a handler. Do we include a type assertion to catch these errors in a more clear way?
